### ISSUE TITLE
 link to repo

### ISSUE THREAD

**Issue by chapmanjacobd** [jawj/zapatos-docs#1]
It would be good to make a link to the GitHub repo at the top of the documentation so it's easy to access it and star it, etc

https://github.com/jawj/zapatos

**Comment by jawj** [comment]
There's a `position: fixed` link to the repo always visible at the top right corner. But since you didn't spot it, I'm guessing it's too subtle?

**Comment by chapmanjacobd** [comment]
I don't see it on mobile

**Comment by jawj** [comment]
Ah, right. It's there on Mobile Safari, but I see on Chrome it ends up way over to the right (out of sight). I'll see if I can fix that.

**Comment by jawj** [comment]
Right, that should be fixed (as soon as the GitHub Pages update), and I also added a GitHub link at the bottom of the navigation menu, just in case. Thanks for pointing this out.
